name: ETL for Bright Books

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  push:
    branchs: [main]
    paths:
      - etl.py
      - requirements.txt

jobs:
  etl:
    runs-on: ubuntu-latest
    env:
      SOURCE_URL: SHEET_ID
      PAGE_SIZE: "100"
      DATABASE_ID: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETL
        env:
          SHEET_ID: ${{ vars.SHEET_ID }}
          GOOGLE_SA_KEY_JSON: ${{ secrets.GOOGLE_SA_KEY_JSON }}
          DB_NAME: ${{ secrets.BD_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          PG_DB: ${{ secrets.PG_DB }}
          PG_TABLE: ${{ secrets.PG_TABLE }}
          WORKSHEET: ${{ secrets.WORKSHEET }}

        run: python etl.py